#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [4]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [4]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[116 360 243 412 258 401 161 407 389 243]
 [324 223 322 275 120 342 171 357 125 464]
 [345 213 350 498 329 193 454 114 142 409]
 [282 187 471 371 462 169 373 398 301 452]
 [334 166 335 329 351 354 175 316 176 118]
 [201 120 145 394 388 450 311 445 414 102]
 [221 400 259 167 191 346 328 393 184 243]
 [194 494 361 430 409 387 170 161 402 171]
 [294 339 124 357 477 349 293 301 196 133]
 [168 328 471 237 316 172 312 266 296 435]]


0    1    2    3    4    5    6    7    8    9
0  116  360  243  412  258  401  161  407  389  243
1  324  223  322  275  120  342  171  357  125  464
2  345  213  350  498  329  193  454  114  142  409
3  282  187  471  371  462  169  373  398  301  452
4  334  166  335  329  351  354  175  316  176  118
5  201  120  145  394  388  450  311  445  414  102
6  221  400  259  167  191  346  328  393  184  243
7  194  494  361  430  409  387  170  161  402  171
8  294  339  124  357  477  349  293  301  196  133
9  168  328  471  237  316  172  312  266  296  435

In [9]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.99982241 0.94510457 0.10473934]
 [0.20437668 0.36214064 0.04196877]
 [0.18063641 0.70641994 0.43725158]
 [0.50515941 0.22383169 0.16175685]
 [0.695225   0.8897124  0.75417758]]


колонка 1  колонка 2  колонка 3
0   0.999822   0.945105   0.104739
1   0.204377   0.362141   0.041969
2   0.180636   0.706420   0.437252
3   0.505159   0.223832   0.161757
4   0.695225   0.889712   0.754178

In [4]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [22]:
a

Петя      Вася    Микола
10  0.812944  0.324553  0.446260
20  0.604526  0.520530  0.380109
30  0.428304  0.980118  0.915512
40  0.543106  0.080319  0.614031
50  0.916925  0.561515  0.815545

In [5]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [6]:
str(name_rik[2])

"('Микола', 2003)"

In [7]:
pd.read_csv?

In [8]:
!echo "Вася, 2001\nПетя, 2000,\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

"cat" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte

### ЗАВДАННЯ

In [18]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame(np.random.randint(1, 50, 10))
df1_1

0
0   2
1  22
2  28
3  38
4  46
5   5
6  39
7  29
8  26
9   3

In [19]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
mat = np.random.randint(10, 100, (5, 6), dtype="int16")
df1_2 = pd.DataFrame(mat)
df1_2

0   1   2   3   4   5
0  65  81  90  11  78  68
1  38  72  26  36  18  58
2  70  44  44  88  91  53
3  75  26  64  71  55  15
4  26  30  11  56  28  54

ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [25]:
name = ["Петро", "Іван", "Степан"]
surname = ["Петро", "Іванов", "Степанов"]
year = [2000, 2002, 2001]
phone = ["222-222-2222", "333-333-3333", "444-444-4444"]

data = list(zip(name, surname, year, phone))
df1_3 = pd.DataFrame(data, columns = ["ім'я", "прізвище", "рік народження", "телефон"])
df1_3

ім'я  прізвище  рік народження       телефон
0   Петро     Петро            2000  222-222-2222
1    Іван    Іванов            2002  333-333-3333
2  Степан  Степанов            2001  444-444-4444

In [29]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls

file_name = 'ЖУРНАЛ ФІТ 3 курс.xlsx'
df1_4 = pd.read_excel(file_name, header=1)
df1_4[:20]

N           Прізвище  Логін на Мооdle   Разовий PSW  \
0    NaN      Аврамчук А. Ю.     avramchuk_a        111111   
1    NaN         Балан А. М.         balan_a        111111   
2    1.0      Безпалий О. С.      bezpalij_o        111111   
3    2.0        Будова М. І.        budova_m        111111   
4    3.0          Вовк А. О.          vovk_a        111111   
5    4.0         Годес О. Є.         godes_o        111111   
6    5.0       Гученко О. П.      guchenko_o        111111   
7    6.0   Данильченко Д. І.  daniljchenko_d        111111   
8    7.0      Джарадат М. Т.     dzharadat_m        111111   
9    8.0        Донець О. С.        donecj_o        111111   
10   9.0         Ємчук З. В.       yemchuk_z        111111   
11  10.0    Жибловська П. Д.   zhiblovsjka_p        111111   
12  11.0        Жончук Н. І.      zhonchuk_n        111111   
13  12.0     Кононенко О. В.     kononenko_o        111111   
14  13.0    Котелевець К. М.    kotelevecj_k        111111   
15  14.0        Котляр С. Ю.       kotlyar_s        111111   
16  15.0        Крюков К. І.       kryukov_k        111111   
17  16.0  Куликовський І. В.  kulikovsjkij_і        111111   
18  17.0     Локтіонов Ю. О.     loktonov_yu        111111   
19  18.0      Любецька А. Д.     lyubecjka_a        111111   

                         Репо дисципліни на GitHub  Вступний тест  \
0                    https://github.com/Angelika17            NaN   
1                                              NaN            NaN   
2             https://github.com/Halfdan22/ML-2023            NaN   
3          https://github.com/BudovaMarina/ML-2023            NaN   
4                                              NaN            NaN   
5           https://github.com/HodesAI/godes_o.git            NaN   
6                                              NaN            NaN   
7                                              NaN            NaN   
8                                              NaN            NaN   
9                                              NaN            NaN   
10         https://github.com/Zoya-Yemchuk/ML-2023            NaN   
11                                             NaN            NaN   
12             https://github.com/zhonchuk/ML-2023            NaN   
13  https://github.com/Alex66123/KononenkoOlexey34            NaN   
14                                             NaN            NaN   
15                                             NaN            NaN   
16                                             NaN            NaN   
17                                             NaN            NaN   
18                https://github.com/MyNameIsJesus            NaN   
19                                             NaN            NaN   

    ТЕСТ\nСекція I  ТЕСТ\nPandas   Лаб 1   Лаб 2  ...   Лаб 5   Лаб 6   Лаб 7  \
0             62.0           NaN     NaN     NaN  ...     NaN     NaN     NaN   
1              NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
2             71.0           NaN    93.0    90.0  ...     NaN    94.0     NaN   
3             78.0           NaN    75.0    77.0  ...     NaN     NaN     NaN   
4              NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
5             64.0           NaN     NaN     NaN  ...     NaN     NaN     NaN   
6              NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
7              NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
8              NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
9             76.0           NaN     NaN     NaN  ...     NaN     NaN     NaN   
10            74.0           NaN    94.0    95.0  ...     NaN    86.0     NaN   
11             NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
12             NaN           NaN    90.0     NaN  ...     NaN     NaN     NaN   
13             NaN           NaN     NaN     NaN  ...     NaN     NaN     NaN   
14             NaN           NaN     Na

limit_output extension: Maximum message size of 10000 exceeded with 10361 characters

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [5]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [6]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [34]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [35]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [35]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [37]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [38]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [39]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [40]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [41]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [30]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

NameError: name 'titanic' is not defined

In [42]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [31]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

NameError: name 'titanic' is not defined

### ЗАВДАННЯ

In [7]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [16]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
titanic[['Age', 'Fare']].describe()

Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [17]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
print(f"В датасеті {titanic.dropna().shape[0]} записи, в яких заповнені усі поля")

В датасеті 183 записи, в яких заповнені усі поля


In [19]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
print(f"{titanic[(titanic['Survived'] == 1) & (titanic['Sex']=='female')].shape[0]} жінок, що пережили Титанік")

233 жінок, що пережили Титанік


## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [53]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [54]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [55]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [57]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [59]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       16     Київ
1  Вася  200        9  Бровари
2  Галя   21        8   Фастів

In [60]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       16     Київ
1  Вася   20        9  Бровари
2  Галя   21        8   Фастів

In [61]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       16     Київ
1  Вася        9  Бровари
2  Галя        8   Фастів

In [62]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

In [ ]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

In [ ]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

In [ ]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

In [ ]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

In [ ]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

### ЗАВДАННЯ

In [21]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [22]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df['рік завершення школи'] = [2018, 2020, 200]
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                   200


In [25]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.loc[2, 'рік завершення школи'] = 2020
df.loc[1, 'вік'] = 20
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася   20       3                  2020
2  Галя   21       2                  2020


In [26]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [27]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [29]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
titanic[(titanic.Sex == 'male') & (titanic.Pclass == 2) & (titanic.Age.between(20,30))]

PassengerId  Survived  Pclass  \
72            73         0       2   
117          118         0       2   
120          121         0       2   
134          135         0       2   
135          136         0       2   
178          179         0       2   
213          214         0       2   
219          220         0       2   
221          222         0       2   
234          235         0       2   
242          243         0       2   
308          309         0       2   
342          343         0       2   
343          344         0       2   
361          362         0       2   
398          399         0       2   
418          419         0       2   
529          530         0       2   
551          552         0       2   
562          563         0       2   
619          620         0       2   
655          656         0       2   
658          659         0       2   
666          667         0       2   
685          686         0       2   
728          729         0       2   
733          734         0       2   
734          735         0       2   
848          849         0       2   
861          862         0       2   
864          865         0       2   
883          884         0       2   
886          887         0       2   

                                           Name   Sex   Age  SibSp  Parch  \
72                         Hood, Mr. Ambrose Jr  male  21.0      0      0   
117             Turpin, Mr. William John Robert  male  29.0      1      0   
120                 Hickman, Mr. Stanley George  male  21.0      2      0   
134              Sobey, Mr. Samuel James Hayden  male  25.0      0      0   
135                          Richard, Mr. Emile  male  23.0      0      0   
178                          Hale, Mr. Reginald  male  30.0      0      0   
213                 Givard, Mr. Hans Kristensen  male  30.0      0      0   
219                          Harris, Mr. Walter  male  30.0      0      0   
221                        Bracken, Mr. James H  male  27.0      0      0   
234           Leyson, Mr. Robert William Norman  male  24.0      0      0   
242             Coleridge, Mr. Reginald Charles  male  29.0      0      0   
308                         Abelson, Mr. Samuel  male  30.0      1      0   
342                  Collander, Mr. Erik Gustaf  male  28.0      0      0   
343  Sedgwick, Mr. Charles Frederick Waddington  male  25.0      0      0   
361                   del Carlo, Mr. Sebastiano  male  29.0      1      0   
398                            Pain, Dr. Alfred  male  23.0      0      0   
418                  Matthews, Mr. William John  male  30.0      0      0   
529                 Hocking, Mr. Richard George  male  23.0      2      1   
551                 Sharp, Mr. Percival James R  male  27.0      0      0   
562                  Norman, Mr. Robert Douglas  male  28.0      0      0   
619                         Gavey, Mr. Lawrence  male  26.0      0      0   
655                   Hickman, Mr. Leonard Mark  male  24.0      2      0   
658                Eitemiller, Mr. George Floyd  male  23.0      0      0   
666                 Butler, Mr. Reginald Fenton  male  25.0      0      0   
685      Laroche, Mr. Joseph Philippe Lemercier  male  25.0      1      2   
728             Bryhl, Mr. Kurt Arnold Gottfrid  male  25.0      1      0   
733                  Berriman, Mr. William John  male  23.0      0      0   
734                Troupiansky, Mr. Moses Aaron  male  23.0      0      0   
848                           Harper, Rev. John  male  28.0      0      1   
861                 Giles, Mr. Frederick Edward  male  21.0      1      0   
864                      Gill, Mr. John William  male  24.0      0      0   
883               Banfield, Mr. Frederick James  male  28.0      0      0   
886                       Montvila, Rev. Juozas  male  27.0      0      0   

               Ticket     Fare Cabin Embarked  
72       S.O.C. 14879  73.5000   NaN        S

limit_output extension: Maximum message size of 10000 exceeded with 10201 characters

In [30]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = titanic['Fare'].dropna()
df

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [35]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
cond = titanic['Pclass'] == 1
avg_prise = titanic[cond]['Fare'].mean()
print(f"Середня вартість квитка у каютах 1-го класу: {avg_prise}")

Середня вартість квитка у каютах 1-го класу: 84.1546875


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [63]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [64]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64


In [65]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Sex, dtype: int64

In [66]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

Embarked           C          Q          S
Pclass                                    
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

### ЗАВДАННЯ

In [37]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
group_by_class = titanic.groupby(['Sex'])
max_age = group_by_class['Age'].max()
print(max_age)

Sex
female    63.0
male      80.0
Name: Age, dtype: float64


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [53]:
surv_table = titanic.pivot_table(values="Survived", index="Pclass", columns="Sex", aggfunc='sum')
surv_table



Sex     female  male
Pclass              
1           91    45
2           70    17
3           72    47